{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Nicky D's Sammies and Subs",
    "description" : "This is an API for a restaurant with full CRUD",
    "version" : "1.0.2"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/DiMartinoNicholas/nicky-ds-sammies-and-subs/1.0.2",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "paths" : {
    "/login" : {
      "post" : {
        "summary" : "User login",
        "operationId" : "loginUser",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/login_body"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Successful login",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200"
                }
              }
            }
          },
          "401" : {
            "description" : "Unauthorized - Invalid credentials"
          }
        }
      }
    },
    "/logout" : {
      "post" : {
        "summary" : "User logout",
        "operationId" : "logoutUser",
        "responses" : {
          "200" : {
            "description" : "Successful logout"
          },
          "401" : {
            "description" : "Unauthorized - No valid token provided"
          }
        },
        "security" : [ {
          "bearerAuth" : [ ]
        } ]
      }
    },
    "/sandwiches" : {
      "get" : {
        "summary" : "Get all sandwiches",
        "operationId" : "getSandwiches",
        "responses" : {
          "200" : {
            "description" : "A list of sandwiches",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Sandwich"
                  }
                },
                "examples" : {
                  "example1" : {
                    "summary" : "Classic Italian Sub",
                    "value" : [ {
                      "id" : "1",
                      "name" : "Classic Italian Sub",
                      "ingredients" : [ "Salami", "Ham", "Provolone", "Lettuce", "Tomato", "Onion", "Italian Dressing" ],
                      "price" : 8.99
                    } ]
                  },
                  "example2" : {
                    "summary" : "Turkey Avocado Club",
                    "value" : [ {
                      "id" : "2",
                      "name" : "Turkey Avocado Club",
                      "ingredients" : [ "Turkey", "Bacon", "Avocado", "Swiss Cheese", "Lettuce", "Tomato", "Mayo" ],
                      "price" : 9.99
                    } ]
                  }
                }
              }
            }
          }
        }
      },
      "post" : {
        "summary" : "Create a new sandwich",
        "operationId" : "createSandwich",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Sandwich"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "Sandwich created",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Sandwich"
                }
              }
            }
          }
        }
      }
    },
    "/sandwiches/{sandwichId}" : {
      "get" : {
        "summary" : "Get a sandwich by ID",
        "operationId" : "getSandwichById",
        "parameters" : [ {
          "name" : "sandwichId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "A sandwich object",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Sandwich"
                },
                "examples" : {
                  "example1" : {
                    "summary" : "Classic Italian Sub",
                    "value" : {
                      "id" : "1",
                      "name" : "Classic Italian Sub",
                      "ingredients" : [ "Salami", "Ham", "Provolone", "Lettuce", "Tomato", "Onion", "Italian Dressing" ],
                      "price" : 8.99
                    }
                  },
                  "example2" : {
                    "summary" : "Turkey Avocado Club",
                    "value" : {
                      "id" : "2",
                      "name" : "Turkey Avocado Club",
                      "ingredients" : [ "Turkey", "Bacon", "Avocado", "Swiss Cheese", "Lettuce", "Tomato", "Mayo" ],
                      "price" : 9.99
                    }
                  }
                }
              }
            }
          },
          "404" : {
            "description" : "Sandwich not found"
          }
        }
      },
      "put" : {
        "summary" : "Update a sandwich",
        "operationId" : "updateSandwich",
        "parameters" : [ {
          "name" : "sandwichId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Sandwich"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Sandwich updated",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Sandwich"
                }
              }
            }
          }
        }
      },
      "delete" : {
        "summary" : "Delete a sandwich",
        "operationId" : "deleteSandwich",
        "parameters" : [ {
          "name" : "sandwichId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "204" : {
            "description" : "Sandwich deleted"
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Sandwich" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string"
          },
          "ingredients" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "price" : {
            "type" : "number",
            "format" : "float"
          }
        }
      },
      "login_body" : {
        "type" : "object",
        "properties" : {
          "username" : {
            "type" : "string"
          },
          "password" : {
            "type" : "string"
          }
        }
      },
      "inline_response_200" : {
        "type" : "object",
        "properties" : {
          "token" : {
            "type" : "string"
          }
        }
      }
    },
    "securitySchemes" : {
      "bearerAuth" : {
        "type" : "http",
        "scheme" : "bearer",
        "bearerFormat" : "JWT"
      }
    }
  }
}